cmake_minimum_required(VERSION 3.10)
project(functors)

add_executable(functors functors_demo.cpp)
add_executable(1_element_pridicate 1_element_pridicate.cpp)
add_executable(2_element_pridicate 2_element_pridicate.cpp)
add_executable(Arithmetic_imitation_function Arithmetic_imitation_function.cpp)
add_executable(Relationship_imitation_function Relationship_imitation_function.cpp)
add_executable(Logic_imitation_function Logic_imitation_function.cpp)