project(map)
cmake_minimum_required(VERSION 3.10)


add_executable(1.map_construct_fun 1.map_construct_fun.cpp)
add_executable(2.map_capacity_swap 2.map_capacity_swap.cpp)
add_executable(3.map_insert_delete 3.map_insert_delete.cpp)
add_executable(4.map_search_compute 4.map_search_compute.cpp)
add_executable(5.map_sort 5.map_sort.cpp)